In [1]:
import numpy as np

# numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi=[[10,20,30],[40,50,60],[70,80,90]]

In [6]:
type(matrixListesi)

list

In [10]:
matrixListesi[2][1]

80

In [11]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
yeniList=list(range(0,10,2))

In [18]:
yeniList

[0, 2, 4, 6, 8]

In [19]:
for i in yeniList:
    print(i)

0
2
4
6
8


In [20]:
yeniList[2]

4

In [21]:
print(yeniList)

[0, 2, 4, 6, 8]


# arange . arange ve linspace çok önemli

In [24]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ones

In [28]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# linspace :belirttiğiniz numaralar araısnda eşit aralık bırakarak bir dizi oluşturur. verilen aralığı, verilen sayı kadar böler ve aralığı eşit parçalar olacak şekilde ayarlar

In [30]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [33]:
np.linspace(0,100,300)

array([  0.        ,   0.33444816,   0.66889632,   1.00334448,
         1.33779264,   1.6722408 ,   2.00668896,   2.34113712,
         2.67558528,   3.01003344,   3.34448161,   3.67892977,
         4.01337793,   4.34782609,   4.68227425,   5.01672241,
         5.35117057,   5.68561873,   6.02006689,   6.35451505,
         6.68896321,   7.02341137,   7.35785953,   7.69230769,
         8.02675585,   8.36120401,   8.69565217,   9.03010033,
         9.36454849,   9.69899666,  10.03344482,  10.36789298,
        10.70234114,  11.0367893 ,  11.37123746,  11.70568562,
        12.04013378,  12.37458194,  12.7090301 ,  13.04347826,
        13.37792642,  13.71237458,  14.04682274,  14.3812709 ,
        14.71571906,  15.05016722,  15.38461538,  15.71906355,
        16.05351171,  16.38795987,  16.72240803,  17.05685619,
        17.39130435,  17.72575251,  18.06020067,  18.39464883,
        18.72909699,  19.06354515,  19.39799331,  19.73244147,
        20.06688963,  20.40133779,  20.73578595,  21.07

# eye

In [35]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

# random


In [40]:
np.random.randn(4,2)

array([[ 0.1780858 , -1.61304451],
       [ 0.59866795, -0.18658005],
       [ 0.66100734, -1.792521  ],
       [ 0.14259039,  0.14856761]])

In [41]:
np.random.randint(1,10)

8

In [42]:
np.random.randint(0,25,8)

array([18, 22, 10, 18, 13, 24, 20,  8])

# numpy dizi methodları

In [44]:
benimNumpyDizim=np.arange(30)

In [45]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
benimRandomDizim=np.random.randint(0,100,30)

In [61]:
benimRandomDizim

array([77, 33, 62, 72, 58, 36, 95, 47, 88, 79, 71, 85, 92, 76, 66, 49, 52,
       74, 68, 17, 45, 10, 63, 74, 42, 53, 76, 27, 80, 61])

In [62]:
benimNumpyDizim.reshape(5,6) # 5*6=30 , 30 eleman olduğu için hata vermedi

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [63]:
benimNumpyDizim.max()

29

In [64]:
benimRandomDizim.max()

95

In [65]:
benimRandomDizim.min()

10

In [66]:
benimRandomDizim.reshape(5,6)

array([[77, 33, 62, 72, 58, 36],
       [95, 47, 88, 79, 71, 85],
       [92, 76, 66, 49, 52, 74],
       [68, 17, 45, 10, 63, 74],
       [42, 53, 76, 27, 80, 61]])

In [67]:
benimRandomDizim.argmax() # max sayının hangi indiste olduğunu dönderir

6

In [68]:
benimRandomDizim.argmin() # min sayının indisini dönderir

21

In [69]:
benimNumpyDizim.shape

(30,)

In [70]:
reshapeDizim=benimRandomDizim.reshape(5,6)

In [71]:
reshapeDizim.shape

(5, 6)