In [5]:
import numpy as np

In [6]:
benimDizim=np.arange(0,15)

In [7]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
benimDizim[5]

5

In [9]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [10]:
benimDizim[3:8]=-7

In [11]:
benimDizim

array([ 0,  1,  2, -7, -7, -7, -7, -7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
baskaDizi=np.arange(0,24)

In [14]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingDizisi=baskaDizi[4:12]

In [16]:
slicingDizisi

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
baskaDizi


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
slicingDizisi[:]=700

In [20]:
slicingDizisi

array([700, 700, 700, 700, 700, 700, 700, 700])

In [21]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700, 700, 700, 700,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [22]:
# dizinin değişmemsi için copy() metodu ile kopyalayıp o kopyası üzerinden
# işlemler yapılmalı

In [23]:
kopyalanmisDizi=baskaDizi.copy()

In [24]:
kopyalanmisDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700, 700, 700, 700,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## matrix

In [28]:
benimListem=[[10,20,30],[40,50,60],[70,80,90]]

In [29]:
benimMatrixDizim=np.array(benimListem)

In [30]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
benimMatrixDizim[2]

array([70, 80, 90])

In [32]:
benimMatrixDizim[0][2]

30

In [33]:
benimMatrixDizim[0,1]

20

In [34]:
benimMatrixDizim[0:,2]

array([30, 60, 90])

In [39]:
benimMatrixDizim[1:,1:]

array([[50, 60],
       [80, 90]])

In [46]:
benimMatrixDizim[[0,1]]

array([[10, 20, 30],
       [40, 50, 60]])

## operasyonlar

In [49]:
yeniBirDizi=np.random.randint(1,100,20)

In [50]:
yeniBirDizi

array([78, 46, 35, 74, 56, 53,  7, 53, 86, 95, 99, 41, 82, 40, 36, 14, 32,
       59,  1, 92])

In [51]:
yeniBirDizi>24

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True])

In [52]:
sonucDizisi=yeniBirDizi>24 # dizi filtreleme 1

In [53]:
yeniBirDizi[sonucDizisi]

array([78, 46, 35, 74, 56, 53, 53, 86, 95, 99, 41, 82, 40, 36, 32, 59, 92])

In [54]:
yeniBirDizi

array([78, 46, 35, 74, 56, 53,  7, 53, 86, 95, 99, 41, 82, 40, 36, 14, 32,
       59,  1, 92])

In [56]:
yeniBirDizi[yeniBirDizi>24] #dizi filtreleme 2

array([78, 46, 35, 74, 56, 53, 53, 86, 95, 99, 41, 82, 40, 36, 32, 59, 92])

In [57]:
sonDizi=np.arange(0,24)

In [58]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [60]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [61]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [62]:
sonDizi/sonDizi # ilk elean 0 0 a bölünmez . diğerlerini böldü

C:\Users\sumeyye\AppData\Local\Temp/ipykernel_9048/1954055075.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [70]:
sonDiziShape=np.sqrt(sonDizi)

In [72]:
sonDiziShape.reshape(6,4)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])